INDEX_DATA['IDT4ILMN_Nex'] = {
    "kitName": "IDT-ILMN Nextera DNA UD Indexes - Nextera DNA Flex",
    "indexSetNames":["Set A", "Set B", "Set C", "Set D"],
    "defaultReadLength": 151,
    "indexLength": 10,
    "trimTarget1": "CTGTCTCTTATACACATCT",
    "trimTarget2": "CTGTCTCTTATACACATCT",
    "adapterExtra1": "ATCTCG",
    "adapterExtra2": "GTGTAG",
    "indexSeq":[
      // set A
      {
        "i5":[
          ['CGCTCCACGA', 'CACTATCAAC', 'TTGCTGCCGA', 'CCATCTCGCC', 'TGTAATCGAC', 'TTCAGTTGTC', 'CGTGTACCAG', 'CCAGTCGACG', 'TATGCCTTAC', 'AGCCTATGAT', 'AGTCAGACGA', 'AAGATACACG'],
          ['TATCTTGTAG', 'TGTCGCTGGT', 'CCATCATTAG', 'TTGCTCTATT', 'CACGGCTAGT', 'CCTGACCACT', 'TACACGTTGA', 'TTGACTAGTA', 'CGCAGCAATT', 'CCTTCTAACA', 'TCGCTATGAG', 'TTCATGGTTC'],
          ['AGCTACTATA', 'ACAGTGTATG', 'AGAGGCAACC', 'AATGGATTGA', 'TCACCAACTT', 'AACCATAGAA', 'TCACAACAGT', 'AACGGTCTAT', 'GGAATTGTAA', 'TACATCCATC', 'TAATGTGTCT', 'TATGATGGCC'],
          ['CCACCAGGCA', 'AGCGCCACAC', 'GCCATGTGCG', 'CCGCATACGA', 'AATATTGCCA', 'TGGCCGGATT', 'AAGGACGCAC', 'CTGGAACTGT', 'GTGCTAGGTT', 'TGACGGCCGT', 'AACATCGCGC', 'GGAAGTATGT'],
          ['AGGATAATGT', 'CCTTCGTGAT', 'AGGACAGGCC', 'CGAGGTCGGA', 'CGCGGTGATC', 'AACCTTATGG', 'AGGATGTGCT', 'CTACATGCCT', 'TCCACACAGA', 'GTAAGCAACG', 'AGTACTCATG', 'ATTGCACATA'],
          ['ACAAGTGGAC', 'AGTAGAGCCG', 'CCTAACACAG', 'ATTCCATAAG', 'ACGGATGGTA', 'TGGTAGAGAT', 'TGCGACGGAA', 'TGAGACTTGC', 'TTGGAATTCC', 'TATGTAGTCA', 'GTATTGACGT', 'CACCTTAATC'],
          ['TACTGTTCCA', 'TCGTGCATTC', 'ACGTTCCTTA', 'GTCCGTAAGC', 'TTCCTACAGC', 'TTCGCCACCG', 'AGTGGTTAAG', 'GCGGAGCCAA', 'AAGCGCGCTT', 'AACGAGGCCG', 'AGGAGGTATC', 'TTGTCTACAT'],
          ['ATTAACAAGG', 'CTATAGTCTT', 'TTACAGTTAG', 'CCGTATGTTC', 'CATTAGTGCG', 'CCTATTGTTA', 'TATCCGAGGC', 'AGTATCAGTT', 'ACAACGCTCA', 'CGGATGCTTG', 'ACTTACGGAT', 'CACCGATGTG']
        ],
        "i7":[
          ['GAACTGAGCG', 'GACTGAGTAG', 'GAGAATGGTT', 'AACCATAGAA', 'TGATTATACG', 'ACTCGGCAAT', 'AGTGTTGCAC', 'TCTATCCTAA', 'TAATGTGTCT', 'CCTGCGGAAC', 'TGTCGCTGGT', 'GTCCGTAAGC'],
          ['AGGTCAGATA', 'AGTCAGACGA', 'AGAGGCAACC', 'GGTTGCGAGG', 'CAGCCGCGTA', 'GTCTAATGGC', 'GACACCATGT', 'CTCGCTTCGG', 'ATACCAACGC', 'TTCATAAGGT', 'ACCGTTACAA', 'ACTTCAAGCG'],
          ['CGTCTCATAT', 'CCGTATGTTC', 'CCATCATTAG', 'TAAGCATCCA', 'GGTAACTCGC', 'CCATCTCGCC', 'CCTGTCTGTC', 'CTGTTGGTCC', 'AGGATGTGCT', 'CTCTGCAGCG', 'TATGCCTTAC', 'TCAGAAGGCG'],
          ['ATTCCATAAG', 'GAGTCATAGG', 'GATAGGCCGA', 'ACCACGACAT', 'ACCGGCCGTA', 'CTGCGAGCCA', 'TGATGTAAGA', 'TTACCTGGAA', 'CACGGAACAA', 'CTGACTCTAC', 'ACAAGTGGAC', 'GCGTTGGTAT'],
          ['GACGAGATTA', 'CTTGCCATTA', 'ATGGTTGACT', 'GCCGCACTCT', 'TGTAATCGAC', 'CGTTATTCTA', 'GGAATTGTAA', 'TGGCTAATCA', 'TGGAGTACTT', 'TCTGGTATCC', 'TGGTACCTAA', 'ACATATCCAG'],
          ['AACATCGCGC', 'GAAGCGGCAC', 'TATTGCGCTC', 'CCACCAGGCA', 'GTGCAGACAG', 'AGATCCATTA', 'GCATAAGCTT', 'AACACTGTTA', 'GTATTGACGT', 'CATTAGTGCG', 'TTGGAATTCC', 'TCATAGATTG'],
          ['CTAGTGCTCT', 'TCCATTGCCG', 'ACGCCTTGTT', 'GTGACACGCA', 'CAATCGGCTG', 'GTCCTGGATA', 'CTGAGGAATA', 'ATTGCGCGGT', 'CTTGTACACC', 'ACGGTCAGGA', 'CCTCTACATG', 'GTATTCCACC'],
          ['GATCAAGGCA', 'CGGTTACGGC', 'TTCTACATAC', 'ACAGTGTATG', 'TATGTAGTCA', 'CAGTGGCACT', 'AACGCACGAG', 'TGGCGCGAAC', 'ACACAGGTGG', 'GGCAAGCCAG', 'GGAGCGTGTA', 'CCTCCGTCCA']
        ]
      },
      // set B
      {
        "i5":[
          ['TTGTATCAGG', 'ATACATCACA', 'CTGAGCCGGT', 'TAGCATAACC', 'TTAACCTTCG', 'CTCGAATATA', 'TATGACAATC', 'CTGAGGAATA', 'GTAACTGAAG', 'TCATAGATTG', 'TCGACATCTC', 'TGATGTAAGA'],
          ['CACAACTTAA', 'TATTGCGCTC', 'TCAGATTAAC', 'ACCGTGTGGT', 'CAGTGGCACT', 'TATCGGACCG', 'ATAGCGGAAT', 'TCAGAAGGCG', 'ACGGTCAGGA', 'ATCAGTACCA', 'ACATATCCAG', 'AGGTATGGCG'],
          ['TCACTGTCCG', 'ACAGTAAGAT', 'ACGTTAGCCG', 'AGAGAACCTA', 'ATACTTGTTC', 'ACTCTATTGT', 'CACAGCGGTC', 'TACTCTGCGC', 'TCTAGGCGCG', 'GTTGGATGAA', 'CTTATTGGCC', 'AAGACATTAG'],
          ['GTTGTAGTGC', 'ACCACGACAT', 'AATTCTTGGA', 'TCGAGCCATA', 'CAGCAATCGT', 'CTAATAACCG', 'CCGGTTCCTA', 'AATTGGCGCC', 'AACTTATCCT', 'TGGTGTTATG', 'GGTGAGTAAT', 'CCTCCGGTTG'],
          ['CCAGGCACCA', 'TGATGGCTAC', 'CAACGTTCGG', 'AACGCACGAG', 'ATCCAGGTAT', 'ACTTGTTATC', 'GTCCACCGCT', 'CGCCATATCT', 'TGTCTGGCCT', 'GCTAATAGGA', 'TCCGCCAATT', 'TGCTACTGCC'],
          ['AGGCCGTGGA', 'TTCTTAACCA', 'TCGGCGGTTA', 'TGCCAACTGG', 'TAGAATTGGA', 'TGTGATAACT', 'CGAATCTATA', 'ACCAAGCAGG', 'CCGTTCAAGG', 'AATCTAGAGA', 'AAGTTGACAA', 'TCTATCCTAA'],
          ['TACACTACAA', 'ACGAACAACA', 'CAGCACGGAG', 'AATGCGAACA', 'CGCTGTCTCA', 'TTACCTGGAA', 'TGGCCTCTGT', 'ATTGTTCGTC', 'GTAGGTGGTG', 'TAGGCTCGCG', 'AGAATTCGCC', 'CTAGATTGCG'],
          ['CGTGTCGTGG', 'ATGTTGTTGG', 'AGCTGGAATG', 'CGATGCGGTT', 'TAATTAGCGT', 'CCTCTACATG', 'CAATAGGAAT', 'TGGACCGCCA', 'ATACAAGCAA', 'AGAGCTTATC', 'GCTGACGTTG', 'AGTACAACTC']
        ],
        "i7":[
          ['TGCCGGTCAG', 'CAGCAATCGT', 'GAATTACAAG', 'AGAGAACCTA', 'TCTAGGCGCG', 'CCGGTTCCTA', 'TATGATGGCC', 'CCACGCTGAA', 'AATTCCATCT', 'ATGTTGTTGG', 'CTCGAATATA', 'ACGGTCCAAC'],
          ['CACTCAATTC', 'TTCTGTAGAA', 'TAGAATTGGA', 'GATATTGTGT', 'ATAGCCAAGA', 'GGCCAATATT', 'CGCAGCAATT', 'GTTCGGAGTT', 'TTAACGGTGT', 'GCACCACCAA', 'GATCGTCGCG', 'GTAACTTGGT'],
          ['TCTCACACGC', 'GAACGCAATA', 'AGGCAGCTCT', 'CGTACAGGAA', 'TTCGGTGTGA', 'GAATACCTAT', 'ACGTTCCTTA', 'ATAGCGGAAT', 'ACTTGTTATC', 'AGGCGTTCGC', 'TATCCGAGGC', 'AGCGCCACAC'],
          ['TCAATGGAGA', 'AGTACTCATG', 'ATCGGCGAAG', 'CTGCGTTACC', 'ATGTAACGTT', 'TACGTGAAGG', 'CCGCGTATAG', 'GCAATATTCA', 'CGTGTACCAG', 'CCTCCGGTTG', 'CGCTGTCTCA', 'TGCTACTGCC'],
          ['ATATGCATGT', 'GGTAGAATTA', 'CCGTGACCGA', 'AGGCCGTGGA', 'AACGAGGCCG', 'CTTATTGGCC', 'GATTCTGAAT', 'CTAGATTGCG', 'TTAACCTTCG', 'GTCCACCGCT', 'AATGCGAACA', 'CAACACCGCA'],
          ['ATGGCGCCTG', 'TAATTAGCGT', 'ATACTTGTTC', 'AGGAGGTATC', 'TGGTGTTATG', 'ACAACTACTG', 'TAGAGAATAC', 'CGATGCGGTT', 'CATATGCGAT', 'ATTGTTCGTC', 'AATTCTTGGA', 'CACCTTAATC'],
          ['TCCGTTATGT', 'ATTAACAAGG', 'TCCGCCAATT', 'GCTGACGTTG', 'TGGCCTCTGT', 'GTTGGATGAA', 'TTGTATCAGG', 'TCCGGACTAG', 'AGCCTATGAT', 'GGACCAGTGG', 'TTCCTACAGC', 'TTGAATGTTG'],
          ['GGTCTATTAA', 'TGATGGCTAC', 'AGGACAGGCC', 'CTAATAACCG', 'CCAGGCACCA', 'AATCCAATTG', 'CACAGCGGTC', 'GTGACGGAGC', 'TATGACAATC', 'CCTTCTAACA', 'ATCCAGGTAT', 'CCGGTAACAC']
        ]
      },
      // set C
      {
        "i5":[
          ['TCCACGTGTT', 'TCCAGAGATC', 'ATGTCGTATT', 'CATTAACTGA', 'TATAGGTACT', 'TGAACACCTG', 'TCCTTCGAAG', 'TTGTCCGCTG', 'GTATACAGAG', 'GGTTGCGAGG', 'CGGCACACTC', 'ATGTAACGTT'],
          ['CCGGTAACAC', 'ATGGCGCCTG', 'GCCATATAAC', 'TCAAGGTCAC', 'ATCTCCGGTC', 'CCTGTCTGTC', 'CTGACTCTAC', 'ATGCGGATCC', 'CACCTGTTGC', 'ACAGCTATAC', 'TCCGGACTAG', 'GAGCTTGCCG'],
          ['GTAACAATCT', 'GGTCTATTAA', 'CATGGCAGGC', 'ATATGCATGT', 'AGGCTGAACG', 'AACAAGTACA', 'TGACAATGTC', 'CAACACCGCA', 'CTGCGTTACC', 'CTAATGTAGC', 'GCGTATTAAT', 'ATAGCCAAGA'],
          ['CATTGGTCAA', 'TCGCGACTCC', 'ATAGGTCTTA', 'TAGGTATGTT', 'GAGGAAGTAA', 'CTACTTAGAG', 'GCCTTGCGGA', 'TCCGTTATGT', 'ATTGCGCGGT', 'AAGATTCGTA', 'ATACTCTAGG', 'CGCATTCCGT'],
          ['TGCCGGTCAG', 'CTCTGGCGTT', 'CCATGGTATA', 'CTACACATGG', 'GGTGGACGTG', 'CTGTGGTGAC', 'ATAAGGCAGT', 'CGCGAACGTC', 'TGTTCCGGCT', 'TGCGCTCCTA', 'AGTCTTCCTA', 'CCTGCGGAAC'],
          ['ATTGATGAGA', 'GTTAATTACG', 'AACAGACGGC', 'GGAGAGACTC', 'AGATAGTAGC', 'GGTATGTAGA', 'TACGTGCGTA', 'TTGTTGAATG', 'CTTCCTAGGA', 'ACGCCAGTAC', 'AAGGCCACGG', 'GTAACTTGGT'],
          ['CTGTTGGTCC', 'TCAGTCTCGT', 'TATCACTCTG', 'TGCGCATAGC', 'ATGGTTGACT', 'GCCTAACGTG', 'ACTTCAAGCG', 'ATAATCCGTG', 'TTAGGCTCAA', 'GCTCTTAACT', 'GGATATATCC', 'CTGCGAGCCA'],
          ['GCAATACATT', 'CGGCCGATAC', 'ATAGTTAGCA', 'CATATGCGAT', 'TACCGCCTCG', 'AGACTCACCA', 'TGAAGTGCAG', 'CCGTCCTCAA', 'ACACAGGTGG', 'TTATACGCGA', 'CCAAGAGGTG', 'AACGTTAGTT']
        ],
        "i7":[
          ['TCTCATGATA', 'AACCGAGTTC', 'GCTAGACTAT', 'CACTATCAAC', 'TAGTGGAAGC', 'TACAAGACTT', 'TGAACGCGGA', 'ATGTCCAGCA', 'GTAACAATCT', 'TACCGCCTCG', 'CCAATGATAC', 'TATCACTCTG'],
          ['CGAGGCCAAG', 'TGTGATAACT', 'AGCTACTATA', 'TTGCTCTATT', 'CGCCATATCT', 'CTGTGGTGAC', 'CCTGCAACCT', 'CAACGTTCGG', 'CAGCGGTAGA', 'CTGTTATATC', 'GAGGCCTATT', 'AGAATTCGCC'],
          ['TTCACGAGAC', 'AGTATGCTAC', 'CCACCGGAGT', 'TTACAGTTAG', 'GCTTCATATT', 'CTCCACTAAT', 'TTCATGGTTC', 'GCGTATTAAT', 'TCATACCGTT', 'TAACCGGCGA', 'AGCTAAGCGG', 'CCTGACCACT'],
          ['GCGTGGATGG', 'GTAACTGAAG', 'CTTACCGCAC', 'CTAAGTACGC', 'ACTAGCGCTA', 'ATAGTTAGCA', 'ATCCTCTCAA', 'GTTGTGACTA', 'GGCGCCATTG', 'AAGAGAGTCT', 'CTTCCTAGGA', 'AGCTGGAATG'],
          ['TCCTGGTTGT', 'TCCTCGGACT', 'TTAGGATATC', 'TAGTTCGGTA', 'GCTCTTAACT', 'ATAGGTCTTA', 'CACTAGACCA', 'TCTCAATACC', 'AGCGAATTAG', 'GTAGGCGAGC', 'CGATCTGTGA', 'TGATAACGAG'],
          ['TAATTCTGCT', 'CTGGAACTGT', 'TTATACGCGA', 'CTATTACTAC', 'GTGGTATCTG', 'TTCTTAACCA', 'ATTATCCACT', 'AAGCATCTTG', 'TTAGACCATG', 'AACTTATCCT', 'GTGGACAAGT', 'CATAGTAAGG'],
          ['CGCACGACTG', 'GAATATGCGG', 'CGCTTAGAAT', 'TAGCATAACC', 'TGACGGCCGT', 'AAGGAAGAGT', 'ATGGCGTGCC', 'TCAGTCTCGT', 'CACACAGTAT', 'ATTATGTCTC', 'AACAAGTACA', 'ATTGGCTTCT'],
          ['GAGGTTAGAC', 'GATCGGATAA', 'CCGAAGCGCT', 'ACTCTATTGT', 'CAGTAATTAC', 'GGAAGGAGAC', 'TCCAGAGATC', 'TGCAAGATAA', 'TCTTGTCGGC', 'TATAACAGCT', 'AGATTAAGTG', 'GTACCGATTA']
        ]
      },
      // set D
      {
        "i5":[
          ['TCCAACTCTA', 'AAGTTCTAGT', 'TCAATGGAGA', 'CAGACGTGGT', 'TTCGAAGAGG', 'CCTGCAACCT', 'CCAAGGCCTT', 'CGATCGAATT', 'ACATATAGTC', 'TAGCTCACAG', 'GATATTGTGT', 'GTCCAAGCGT'],
          ['CTAGTGCTCT', 'GTAAGCCTAA', 'CTTGGTCTCG', 'TGAGTACAAC', 'AAGAGGATGA', 'CTCCGTATTA', 'GTTGCGTTCA', 'AATGTCGGAA', 'GTTCCGAACG', 'CGATCTGTGA', 'ATTACCTCCA', 'AATCTACTCC'],
          ['CCTGTAGAGT', 'TCTCATGATA', 'ATGTCCAGCA', 'GTTGACCTGA', 'TTATCTTACC', 'TGCGTCTTCG', 'AGCTAAGCGG', 'GGTCGTGCCA', 'CTAGTATCGA', 'ATTGGCTTCT', 'TACGTGAAGG', 'GGAGCGTGTA'],
          ['GGTGTCACCG', 'CTTGTGTGAG', 'CGATACCATC', 'TCCTCGGACT', 'CTGGCTCGTT', 'ATGTGTCAAT', 'TTCCTCGGTG', 'GTGCTGTGGC', 'CATTGTGGTA', 'CGGCTGCAGT', 'CCGCGTATAG', 'CTCTATCGGA'],
          ['ATACCAACGC', 'CACTCAATTC', 'CAATTAAGCC', 'AGATTAAGTG', 'AGATTGTCTA', 'CAATCGGCTG', 'TGATTATACG', 'ACAACTACTG', 'TGGTATACCA', 'ACTAGATGTT', 'CAACTGCAAC', 'CGGCCTTGAG'],
          ['TGTTAGCACA', 'ATATAATCCG', 'AGGAGTCGAG', 'TAACAGAGTA', 'TTCAGCATTG', 'ACGCGTGAGA', 'GTTCTGTCAT', 'CTTGAGAGCT', 'CAACGAGAGC', 'CATAGTAAGG', 'AGGCGCATAA', 'TATGAACTTG'],
          ['TTACTTCTGG', 'TCTGCTTCAA', 'CTCTGTGTAT', 'ATCGAGTCGC', 'ACACCGTGAC', 'CACGTCAGAG', 'TGCAATGAAT', 'TAATTCCAGA', 'TTCACGAGAC', 'GTCTCGCCAC', 'TGTACTGAGA', 'CCTAAGGATT'],
          ['CAGGTATAAG', 'CTTCGCCGTA', 'TCGTCCGAGA', 'CCTTGCCTAG', 'CTTGTACACC', 'TTCCATTCGA', 'CAGGACATGA', 'CTCCACTAAT', 'AGGTGGCCTT', 'TGGATCTGGC', 'TCCGTATACT', 'GTATTCCACC']
        ],
        "i7":[
          ['GAACAATTCC', 'GAAGACTAGA', 'ATACATCACA', 'TTAATAGCAC', 'TCGACGCTAG', 'GAGCTTGCCG', 'TGTAAGGTGG', 'CTGAATTAGT', 'GATATCACAC', 'GTGTACCTTC', 'GCCATATAAC', 'TGAGTACAAC'],
          ['TGTGGTCCGG', 'AGGAGTCGAG', 'TAGGTATGTT', 'CATTCACGCT', 'CTCGTAGGCA', 'AGCTAGCTTC', 'CAACTGCAAC', 'TAAGGAGGAA', 'AGCGCTGTGT', 'ACCTGGCCAA', 'AGTGCGAGTG', 'CCGCGGTTCT'],
          ['CTTCTAAGTC', 'TTCACTCACT', 'CACCTAGCAC', 'GGCACTAAGG', 'AAGTTCTAGT', 'CAATCCTTGT', 'ACATGAGTGA', 'AGCTTACACA', 'TCACCGCGCT', 'TGTCTGGCCT', 'CTGAGCCGGT', 'ATTGATACTG'],
          ['AATATTGCCA', 'GGTCCGCTTC', 'TTCAAGTATG', 'ATTCGGTACA', 'CCAAGAGGTG', 'CACCTGTTGC', 'GCAACCAGTC', 'AACCAGCCAC', 'GATAGCCTTG', 'AGTTAATGCT', 'AACGGTCTAT', 'GGATTATGGA'],
          ['TCGTGCATTC', 'CAACGAGAGC', 'TTAAGACAAG', 'ACTAATCTCC', 'ATATCTGCTT', 'CGTCACCTTG', 'GAGCGACGAT', 'CTTAAGTCGA', 'CCTGGACGCA', 'GGTGAGTAAT', 'GTTGCGTTCA', 'TGGTTCTCAT'],
          ['AAGATACACG', 'ATTGAGGTCC', 'CACCTCTCTT', 'TGTGTTAGTA', 'TGGATCTGGC', 'AATGACTGGT', 'CGAACGCACC', 'GCCTAACGTG', 'TTACGCACCT', 'TACTCTGCGC', 'CTTCAACCAC', 'TCAACCACGA'],
          ['TGCAATGAAT', 'GGAGAGACTC', 'TTCTCGTGCA', 'CAACGACCTA', 'TTGAATCCAA', 'ATGATTCCGG', 'TCTTACGCCG', 'ACTTACTTCA', 'TCGTTGCTGC', 'AGGTATGGCG', 'TCTATTCAGT', 'TATGAACTTG'],
          ['CTATGAAGGA', 'CCGCTCCGTT', 'GCTAGGAAGT', 'CGGTCGGCAT', 'CACGGCTAGT', 'TTAGGCTCAA', 'AGCTGATGTC', 'CGCATTCCGT', 'CGACAAGGAT', 'TCCAGCCTGC', 'CAAGACGTCC', 'AGTGGTTAAG']
        ]
      }
    ],
    "IndexNamingRule": {"i5": function(plate, row, col){let n = ('000' + (plate*96 + row + col*8 + 1)).slice(-4); return "UDP"+n},
                        "i7": function(plate, row, col){let n = ('000' + (plate*96 + row + col*8 + 1)).slice(-4); return "UDP"+n}
                    }
  }
