INDEX_DATA['IDT4ILMN_Tru_V2'] = {
    "kitName": "IDT-ILMN TruSeq DNA-RNA UD Indexes 96 Indexes V2",
    "indexSetNames":['Index 1-96'],
    "defaultReadLength": 151,
    "indexLength": 8,
    "trimTarget1": "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA",
    "trimTarget2": "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT",
    "adapterExtra1": "ATCTCG",
    "adapterExtra2": "GTGTAG",
    "indexSeq":[
      {
        "i5":[
          ["CTAGCGCT","TCTGTTGG","GTGAATAT","CCGCGGTT","AGTTCAGG","TAATACAG","ACTAAGAT","TACCGAGG","ATATGGAT","ATATCTCG","TGCGGCGT","ACACTAAG"],
          ["TCGATATC","CTCACCAA","ACAGGCGC","TTATAACC","GACCTGAA","CGGCGTGA","GTCGGAGC","CGTTAGAA","GCGCAAGC","GCGCTCTA","CATAATAC","GTGTCGGA"],
          ["CGTCTGCG","GAACCGCG","CATAGAGT","GGACTTGG","TCTCTACT","ATGTAAGT","CTTGGTAT","AGCCTCAT","AAGATACT","AACAGGTT","GATCTATC","TTCCTGTT"],
          ["TACTCATA","AGGTTATA","TGCGAGAC","AAGTCCAA","CTCTCGTC","GCACGGAC","TCCAACGC","GATTCTGC","GGAGCGTC","GGTGAACC","AGCTCGCT","CCTTCACC"],
          ["ACGCACCT","TCATCCTT","GACGTCTT","ATCCACTG","CCAAGTCT","GGTACCTT","CCGTGAAG","TCGTAGTG","ATGGCATG","CAACAATG","CGGAACTG","GCCACAGG"],
          ["GTATGTTC","CTGCTTCC","AGTACTCC","GCTTGTCA","TTGGACTC","AACGTTCC","TTACAGGA","CTACGACA","GCAATGCA","TGGTGGCA","TAAGGTCA","ATTGTGAA"],
          ["CGCTATGT","ATTCGTCA","TGGCCGGT","CAAGCTAG","GGCTTAAG","GCAGAATT","CAATGAGC","TAAGTGGT","GTTCCAAT","AGGCAGAG","TTGCCTAG","ACTCGTGT"],
          ["TATCGCAC","GCCTACTG","CAATTAAC","TGGATCGA","AATCCGGA","ATGAGGCC","TGGCAGAT","CGGACAAC","ACCTTGGC","GAATGAGA","CCATTCGA","GTCTACAC"]
        ],
        "i7":[
          ["CCGCGGTT","AGTTCAGG","TAATACAG","ACTAAGAT","TACCGAGG","ATATGGAT","ATATCTCG","TGCGGCGT","ACACTAAG","CAATTAAC","AACTGTAG","TATCGCAC"],
          ["TTATAACC","GACCTGAA","CGGCGTGA","GTCGGAGC","CGTTAGAA","GCGCAAGC","GCGCTCTA","CATAATAC","GTGTCGGA","TGGCCGGT","GGTCACGA","CGCTATGT"],
          ["GGACTTGG","TCTCTACT","ATGTAAGT","CTTGGTAT","AGCCTCAT","AAGATACT","AACAGGTT","GATCTATC","TTCCTGTT","AGTACTCC","CTGCTTCC","GTATGTTC"],
          ["AAGTCCAA","CTCTCGTC","GCACGGAC","TCCAACGC","GATTCTGC","GGAGCGTC","GGTGAACC","AGCTCGCT","CCTTCACC","GACGTCTT","TCATCCTT","ACGCACCT"],
          ["ATCCACTG","CCAAGTCT","GGTACCTT","CCGTGAAG","TCGTAGTG","ATGGCATG","CAACAATG","CGGAACTG","GCCACAGG","TGCGAGAC","AGGTTATA","TACTCATA"],
          ["GCTTGTCA","TTGGACTC","AACGTTCC","TTACAGGA","CTACGACA","GCAATGCA","TGGTGGCA","TAAGGTCA","ATTGTGAA","CATAGAGT","GAACCGCG","CGTCTGCG"],
          ["CAAGCTAG","CAGTAGGC","GCAGAATT","GGCATTCT","TAAGTGGT","GTTCCAAT","GTTCGCCG","TTGCCTAG","ACTCGTGT","ACAGGCGC","CTCACCAA","TCGATATC"],
          ["TGGATCGA","TGACGAAT","ATGAGGCC","AATGCCTC","CGGACAAC","ACCTTGGC","CACGAGCG","CCATTCGA","GTCTACAC","GTGAATAT","TCTGTTGG","CTAGCGCT"]
        ]
      }
    ],
    "IndexNamingRule": {"i5": function(plate, row, col){let n = ('000' + (row + col*8 + 1)).slice(-4); return "UDI"+n},
                        "i7": function(plate, row, col){let n = ('000' + (row + col*8 + 1)).slice(-4); return "UDI"+n}
                    }
  }
