INDEX_DATA["NEBNext_UDI"] = {
    "kitName": "NEBNext UDI",
    "indexSetNames":["Set A", "Set B", "Set C", "Set D"],
    "defaultReadLength": 151,
    "indexLength": 8,
    "trimTarget1": "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA",
    "trimTarget2": "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT",
    "adapterExtra1": "ATCTCG",
    "adapterExtra2": "GTGTAG",
    "indexSeq":[
      // set A
      {
        "i5":[
          ['CGTATTCG', 'CTCCTAGA', 'TAGTTGCG', 'GAGATACG', 'AGGTGTAC', 'TAATGCCG', 'GTCGGTAA', 'AGGTCACT', 'GAATCCGA', 'GTACCTTG', 'CATGAGGA', 'TGACTGAC'],
          ['TCAAGGAC', 'GTTACGCA', 'AGTCTGTG', 'GCACGTAA', 'AACCTTGG', 'ATTGCGTG', 'TCAGACGA', 'GATAGGCT', 'TGGTACAG', 'CAAGGTCT', 'GCTATCCT', 'ATGGAAGG'],
          ['AAGCACTG', 'CTAGCAAG', 'TGCTTCCA', 'GCTTAGCT', 'AACCGTTC', 'GACATTCC', 'ACCTGGAA', 'GGAGATGA', 'GTACTCTC', 'GTAACGAC', 'ATTCCTCC', 'GTGTTCCT'],
          ['GCAATGGA', 'ATCTCGCT', 'GGCTATTG', 'GGTGTCTT', 'TCAACTGG', 'CTTCACCA', 'AGACCGTA', 'GATACTGG', 'TGCGTAGA', 'TCGGTTAC', 'ATGACGTC', 'GCTGTAAG'],
          ['CAATCGAC', 'GTGCCATA', 'TGTTCGAG', 'TGGAGTTG', 'ACGATGAC', 'TGATGTCC', 'ACGGTCTT', 'TCTCGCAA', 'GGAATTGC', 'ACGGATTC', 'TTAAGCGG', 'TGCAGGTA'],
          ['GGCGTTAT', 'GGTGATTC', 'AACTTGCC', 'GCAAGATC', 'TCGCATTG', 'TGTACACC', 'TGAACCTG', 'CTTCGTTC', 'CTTCTGAG', 'TGCTCATG', 'AGTTCGTC', 'TAGCGTCT'],
          ['GTTAAGGC', 'CACCTTAC', 'TGGTAGCT', 'CAGTGAAG', 'GTTCAACC', 'TGGCTATC', 'AGCTCCTA', 'GCAATTCG', 'CTTAGGAC', 'GTCCTAAG', 'AACGTGGA', 'CTGTGTTG'],
          ['CCTATACC', 'TTCTCTCG', 'GTATGCTG', 'AAGTCGAG', 'AACCGAAG', 'TGTTGTGG', 'CTGGAGTA', 'TCTCTTCC', 'TCTAACGC', 'GGTCAGAT', 'CTCTGGTT', 'TGTGGTAC']
        ],
        "i7":[
          ["TTACCGAC", "AGTGACCT", "TCGGATTC", "CAAGGTAC", "TCCTCATG", "GTCAGTCA", "CGAATACG", "TCTAGGAG", "CGCAACTA", "CGTATCTC", "GTACACCT", "CGGCATTA"],
          ["TCGTCTGA", "AGCCTATC", "CTGTACCA", "AGACCTTG", "AGGATAGC", "CCTTCCAT", "GTCCTTGA", "TGCGTAAC", "CACAGACT", "TTACGTGC", "CCAAGGTT", "CACGCAAT"],
          ["TTCCAGGT", "TCATCTCC", "GAGAGTAC", "GTCGTTAC", "GGAGGAAT", "AGGAACAC", "CAGTGCTT", "CTTGCTAG", "TGGAAGCA", "AGCTAAGC", "GAACGGTT", "GGAATGTC"],
          ["TACGGTCT", "CCAGTATC", "TCTACGCA", "GTAACCGA", "GACGTCAT", "CTTACAGC", "TCCATTGC", "AGCGAGAT", "CAATAGCC", "AAGACACC", "CCAGTTGA", "TGGTGAAG"],
          ["AAGACCGT", "TTGCGAGA", "GCAATTCC", "GAATCCGT", "CCGCTTAA", "TACCTGCA", "GTCGATTG", "TATGGCAC", "CTCGAACA", "CAACTCCA", "GTCATCGT", "GGACATCA"],
          ["CAGGTTCA", "GAACGAAG", "CTCAGAAG", "CATGAGCA", "GACGAACT", "AGACGCTA", "ATAACGCC", "GAATCACC", "GGCAAGTT", "GATCTTGC", "CAATGCGA", "GGTGTACA"],
          ["TAGGAGCT", "CGAATTGC", "GTCCTAAG", "CTTAGGAC", "TCCACGTT", "CAACACAG", "GCCTTAAC", "GTAAGGTG", "AGCTACCA", "CTTCACTG", "GGTTGAAC", "GATAGCCA"],
          ["TACTCCAG", "GGAAGAGA", "GCGTTAGA", "ATCTGACC", "AACCAGAG", "GTACCACA", "GGTATAGG", "CGAGAGAA", "CAGCATAC", "CTCGACTT", "CTTCGGTT", "CCACAACA"]
        ]
      },
      // set B
      {
        "i5":[
          ['AGTCGCTT', 'GGATTCGT', 'TGGGTAAT', 'CTACAGTG', 'TCGTGGGA', 'CCTTCCTT', 'TCCTACCT', 'ACAGCCAT', 'TTGACAGG', 'GGCGAACA', 'ACTCCGGT', 'CTATTGAA'],
          ['GCCTATCA', 'ACTCAGAC', 'CACAAGTC', 'TCGTGCAC', 'CTGTTGGT', 'TTGTGTGC', 'TTGCGCGA', 'TACGCCTT', 'GCGGATGG', 'TGCCTTGT', 'TCGTCAAG', 'GAGCAAAC'],
          ['GGCGCTGA', 'CTCACACC', 'CTCCTCGT', 'ATTTCGAG', 'ATACTGAC', 'ACCCGAGG', 'AGGAACAT', 'GTGGTGTT', 'AGTTTAGG', 'CTTACCTG', 'AGGCTTCT', 'GTCGTGGC'],
          ['ATGTGACT', 'TATGCAAG', 'CGAGATTA', 'GTTGTGAG', 'GCTCGAAT', 'AGGTGCTA', 'CCATAATG', 'GAAGAGGT', 'GTGTGACA', 'GTCTCCTT', 'CAACCTAG', 'GTTCCAGA'],
          ['GTGAAAGG', 'GGATTGGC', 'CTGCCGTA', 'GTGGTTAC', 'TACAGGTG', 'AGTCCTCA', 'AAACAAGA', 'GATCGGAC', 'TTCATATC', 'ACCTGACT', 'CTGACACA', 'GTCTAGTG'],
          ['AGGGAAAG', 'ACCGGCAT', 'GATGGGCA', 'TGGATATG', 'AGAGTCGG', 'TTCGGGAA', 'AGTAAGCC', 'TGGTCCTC', 'CCACACTT', 'CTTACGGT', 'CTGGTTCT', 'TAACGCAA'],
          ['GAATTGTC', 'ACGGTATG', 'GACTGCTG', 'GATTAGCG', 'TCCAGCAA', 'ATCGACTC', 'CATATCGT', 'TAAGAGCG', 'ACGCCAAC', 'ACGTCATA', 'TGTCCAAT', 'TGCATAGG'],
          ['AGTCGTGT', 'GCTCTGAT', 'AGCCGGTA', 'GTTGGAAG', 'CGAAGCTG', 'CACAGGTA', 'CTGCGGAT', 'GAGCTCAG', 'GCCAGCTA', 'GTACCCAA', 'CAACGGGT', 'CTCGGTTG']
        ],
        "i7":[
          ["CACTGTAG", "AAGCGACT", "ACGAATCC", "ATTACCCA", "TTCAATAG", "ACCGGAGT", "TGTTCGCC", "CCTGTCAA", "ATGGCTGT", "AGGTAGGA", "AAGGAAGG", "TCCCACGA"],
          ["GTGCACGA", "TGATAGGC", "GTCTGAGT", "GACTTGTG", "GTTTGCTC", "CTTGACGA", "ACAAGGCA", "CCATCCGC", "AAGGCGTA", "TCGCGCAA", "GCACACAA", "ACCAACAG"],
          ["ATGTTCCT", "AACACCAC", "CCTAAACT", "CAGGTAAG", "AGAAGCCT", "GCCACGAC", "TCAGCGCC", "GGTGTGAG", "ACGAGGAG", "CTCGAAAT", "GTCAGTAT", "CCTCGGGT"],
          ["CATTATGG", "ACCTCTTC", "TGTCACAC", "AAGGAGAC", "CTAGGTTG", "TCTGGAAC", "AGTCACAT", "CTTGCATA", "TAATCTCG", "CTCACAAC", "ATTCGAGC", "TAGCACCT"],
          ["TCTTGTTT", "GTCCGATC", "GATATGAA", "AGTCAGGT", "TGTGTCAG", "CACTAGAC", "CCTTTCAC", "GCCAATCC", "TACGGCAG", "GTAACCAC", "CACCTGTA", "TGAGGACT"],
          ["GGCTTACT", "GAGGACCA", "AAGTGTGG", "ACCGTAAG", "AGAACCAG", "TTGCGTTA", "CTTTCCCT", "ATGCCGGT", "TGCCCATC", "CATATCCA", "CCGACTCT", "TTCCCGAA"],
          ["ACGATATG", "CGCTCTTA", "GTTGGCGT", "TATGACGT", "ATTGGACA", "CCTATGCA", "GACAATTC", "CATACCGT", "CAGCAGTC", "CGCTAATC", "TTGCTGGA", "GAGTCGAT"],
          ["ATCCGCAG", "CTGAGCTC", "TAGCTGGC", "TTGGGTAC", "ACCCGTTG", "CAACCGAG", "ACACGACT", "ATCAGAGC", "TACCGGCT", "CTTCCAAC", "CAGCTTCG", "TACCTGTG"]
        ]
      },
      // set C
      {
        "i5":[
          ['TTAGCTTT', 'GTCAGGGT', 'GACGTCGT', 'CTCGACGT', 'GTTCACGT', 'GAGGTATA', 'CTACGACA', 'ATTAGCGC', 'TGCAACAA', 'TAGAGAAA', 'ATCCCAAA', 'TGTGACTA'],
          ['AATCTCCA', 'CCTTCAAC', 'CGTCATAC', 'TCTAGTCA', 'AAAGGGAA', 'ATCAAGAG', 'TATGATTG', 'GCAGCTCT', 'AAGTGTGG', 'ATCGCTGG', 'GCTTGGTG', 'CCACTTCT'],
          ['GTCTAATT', 'TCCCGTGC', 'TTGCTGTA', 'CCCGTCTA', 'CGAGCGTC', 'CTAAGAGT', 'ATAAGAAC', 'TAAGTATG', 'CAAACGGG', 'CACTCCCA', 'CCTCTCCG', 'AATCCACG'],
          ['CCCAAAGT', 'TTTATACG', 'CCCTGCTG', 'TAGAAGAG', 'GACGTGAG', 'TGTTGCTC', 'GTCGCATC', 'CGGTGCAA', 'GGGAGCAT', 'TACGAGGG', 'GGTAAATA', 'GCATCTAC'],
          ['TCCGTCCG', 'CCGTCTCT', 'CATTTATC', 'GGGACGTA', 'CTTGGCAG', 'CGTCACTG', 'CCCTCTTC', 'TATCCCGC', 'TATTGAGC', 'CCATATCG', 'TCCATATA', 'GAGCGGTA'],
          ['GGCTCTGC', 'GACTTGTA', 'CTTGATGC', 'TTTCCATC', 'TGCGGCGT', 'TCAATCTT', 'GATTACTA', 'TTCACTTC', 'CGAACTAC', 'GGGCACAA', 'ATGTTAAC', 'GTGGTTCG'],
          ['GATCATGC', 'AAGATTCA', 'ATGTATCG', 'CGACGAAC', 'GACTGGCG', 'AAACACAC', 'CTCCACAC', 'GTAAACAG', 'GGTTCTCG', 'AGAGGACA', 'CCAAGACG', 'GAACAATA'],
          ['TAGGTCGA', 'CAAGTTGC', 'ATAGGGTT', 'TTGGTCTC', 'TTGTTTAG', 'GTCGGACG', 'TACAACGT', 'GAGTGCTC', 'TACATGGC', 'GACTATAC', 'TCGCTACG', 'CACACAAC']
        ],
        "i7":[
          ["TGTCGTAG", "GCGCTAAT", "TTGTTGCA", "TTTCTCTA", "TTTGGGAT", "TAGTCACA", "AAAGCTAA", "ACCCTGAC", "ACGACGTC", "ACGTCGAG", "ACGTGAAC", "TATACCTC"],
          ["CAATCATA", "AGAGCTGC", "CCACACTT", "CCAGCGAT", "CACCAAGC", "AGAAGTGG", "TGGAGATT", "GTTGAAGG", "GTATGACG", "TGACTAGA", "TTCCCTTT", "CTCTTGAT"],
          ["GTTCTTAT", "CATACTTA", "CCCGTTTG", "TGGGAGTG", "CGGAGAGG", "CGTGGATT", "AATTAGAC", "GCACGGGA", "TACAGCAA", "TAGACGGG", "GACGCTCG", "ACTCTTAG"],
          ["GATGCGAC", "TTGCACCG", "ATGCTCCC", "CCCTCGTA", "TATTTACC", "GTAGATGC", "ACTTTGGG", "CGTATAAA", "CAGCAGGG", "CTCTTCTA", "CTCACGTC", "GAGCAACA"],
          ["GAAGAGGG", "GCGGGATA", "GCTCAATA", "CGATATGG", "TATATGGA", "TACCGCTC", "CGGACGGA", "AGAGACGG", "GATAAATG", "TACGTCCC", "CTGCCAAG", "CAGTGACG"],
          ["TAGTAATC", "GAAGTGAA", "GTAGTTCG", "TTGTGCCC", "GTTAACAT", "CGAACCAC", "GCAGAGCC", "TACAAGTC", "GCATCAAG", "GATGGAAA", "ACGCCGCA", "AAGATTGA"],
          ["GTGTGGAG", "CTGTTTAC", "CGAGAACC", "TGTCCTCT", "CGTCTTGG", "TATTGTTC", "GCATGATC", "TGAATCTT", "CGATACAT", "GTTCGTCG", "CGCCAGTC", "GTGTGTTT"],
          ["ACGTTGTA", "GAGCACTC", "GCCATGTA", "GTATAGTC", "CGTAGCGA", "GTTGTGTG", "TCGACCTA", "GCAACTTG", "AACCCTAT", "GAGACCAA", "CTAAACAA", "CGTCCGAC"]
        ]
      },
      // set D
      {
        "i5":[
          ['CCGGGACT', 'AGCAGACT', 'CTTGTACT', 'ATCCAACT', 'AAGGCAAC', 'TACTGATA', 'GCAGAAGT', 'TCCAGGCT', 'CCCATTGC', 'TTAATGTC', 'CGATCTTT', 'TTACTACT'],
          ['GTCCAGGA', 'GATTCGGC', 'TCACAGTA', 'GCGTGTTA', 'TTCATTGG', 'CTGACTCG', 'CTGCTTAA', 'CTGTCCTC', 'GTGTCCAG', 'ACGTACAT', 'TAGCTCAC', 'CCTTAGTA'],
          ['TCATGTAG', 'ATCATAGT', 'AATTCCGG', 'GTGAGTCT', 'CAACTGAT', 'GATGGAAA', 'GATTTGAT', 'TTCGATAG', 'GCATACTT', 'TTTGTCAT', 'CCCGCGTT', 'TCCGAATG'],
          ['CTATCCGG', 'AGATAGGG', 'CCGAGCGA', 'ACACTCTG', 'GTGTATGT', 'AGTTAAAG', 'GACTCAAA', 'GTTAGTGA', 'CCATCGGA', 'GTAGGTGG', 'AGCACAAG', 'TGACGATT'],
          ['GGCGGGTT', 'GGACAACG', 'TCCGCACT', 'CGTAATGT', 'ATATGGAG', 'ATAGAGGC', 'GAGGATTT', 'CTTATCGA', 'CCGTTGTC', 'CAACAGCA', 'GGGTAAGC', 'AAATCAGC'],
          ['CACGTTCG', 'CCGTTCCA', 'TGTGAAGC', 'GTAGTAAT', 'ACTTAAGC', 'AAAGGAGG', 'CATCTGTA', 'GAATAAAG', 'TAAAGCTA', 'CTGAAATG', 'TGTTTACT', 'CTTTCGCG'],
          ['TTCTACGG', 'CCGAAGGG', 'ACGATCGG', 'AGGGTCCA', 'ATACGTGT', 'GGGAACTG', 'TGCGCTTA', 'GAAGGCAG', 'GACTGTTT', 'TAGGGACG', 'TTACATCG', 'AGTGGCAA'],
          ['AGTAGATG', 'TTTGGACA', 'GCTTACGG', 'TGCAAGCG', 'ACTTCTTG', 'ACAAGGTA', 'TTCCGTTG', 'TTGGTTGT', 'AGTGAGGT', 'TAATCGTA', 'CGACTAGG', 'TCCACGAA']
        ],
        "i7":[
          ["ACTTCTGC", "AGCCTGGA", "GCAATGGG", "GACATTAA", "AAAGATCG", "AGTAGTAA", "AGTCCCGG", "AGTCTGCT", "AGTACAAG", "AGTTGGAT", "GTTGCCTT", "TATCAGTA"],
          ["TTAAGCAG", "GAGGACAG", "CTGGACAC", "ATGTACGT", "GTGAGCTA", "TACTAAGG", "TCCTGGAC", "GCCGAATC", "TACTGTGA", "TAACACGC", "CCAATGAA", "CGAGTCAG"],
          ["ATCAAATC", "CTATCGAA", "AAGTATGC", "ATGACAAA", "AACGCGGG", "CATTCGGA", "CTACATGA", "ACTATGAT", "CCGGAATT", "AGACTCAC", "ATCAGTTG", "TTTCCATC"],
          ["TTTGAGTC", "TCACTAAC", "TCCGATGG", "CCACCTAC", "CTTGTGCT", "AATCGTCA", "CCGGATAG", "CCCTATCT", "TCGCTCGG", "CAGAGTGT", "ACATACAC", "CTTTAACT"],
          ["AAATCCTC", "TCGATAAG", "GACAACGG", "TGCTGTTG", "GCTTACCC", "GCTGATTT", "AACCCGCC", "CGTTGTCC", "AGTGCGGA", "ACATTACG", "CTCCATAT", "GCCTCTAT"],
          ["TACAGATG", "CTTTATTC", "TAGCTTTA", "CATTTCAG", "AGTAAACA", "CGCGAAAG", "CGAACGTG", "TGGAACGG", "GCTTCACA", "ATTACTAC", "GCTTAAGT", "CCTCCTTT"],
          ["TAAGCGCA", "CTGCCTTC", "AAACAGTC", "CGTCCCTA", "CGATGTAA", "TTGCCACT", "CCGTAGAA", "CCCTTCGG", "CCGATCGT", "TGGACCCT", "ACACGTAT", "CAGTTCCC"],
          ["CAACGGAA", "ACAACCAA", "ACCTCACT", "TACGATTA", "CCTAGTCG", "TTCGTGGA", "CATCTACT", "TGTCCAAA", "CCGTAAGC", "CGCTTGCA", "CAAGAAGT", "TACCTTGT"]
        ]
      }
    ],
    "IndexNamingRule": {"i5": function(plate, row, col){let n = ('000' + (96*plate+col*8+row+1)).slice(-3); return "NEBUDI"+n+"_i5"},
                        "i7": function(plate, row, col){let n = ('000' + (96*plate+col*8+row+1)).slice(-3); return "NEBUDI"+n+"_i7"}
                    }
  }
