INDEX_DATA["NEBNext_UDI"] = {
    "kitName": "NEBNext UDI",
    "indexSetNames":["Set A", "Set B", "Set C", "Set D"],
    "defaultReadLength": 151,
    "indexLength": 8,
    "trimTarget1": "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA",
    "trimTarget2": "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT",
    "adapterExtra1": "ATCTCG",
    "adapterExtra2": "GTGTAG",
    "indexSeq":[
      // set A
      {
        "i5":[
          ["CGAATACG", "TCTAGGAG", "CGCAACTA", "CGTATCTC", "GTACACCT", "CGGCATTA", "TTACCGAC", "AGTGACCT", "TCGGATTC", "CAAGGTAC", "TCCTCATG", "GTCAGTCA"],
          ["GTCCTTGA", "TGCGTAAC", "CACAGACT", "TTACGTGC", "CCAAGGTT", "CACGCAAT", "TCGTCTGA", "AGCCTATC", "CTGTACCA", "AGACCTTG", "AGGATAGC", "CCTTCCAT"],
          ["CAGTGCTT", "CTTGCTAG", "TGGAAGCA", "AGCTAAGC", "GAACGGTT", "GGAATGTC", "TTCCAGGT", "TCATCTCC", "GAGAGTAC", "GTCGTTAC", "GGAGGAAT", "AGGAACAC"],
          ["TCCATTGC", "AGCGAGAT", "CAATAGCC", "AAGACACC", "CCAGTTGA", "TGGTGAAG", "TACGGTCT", "CCAGTATC", "TCTACGCA", "GTAACCGA", "GACGTCAT", "CTTACAGC"],
          ["GTCGATTG", "TATGGCAC", "CTCGAACA", "CAACTCCA", "GTCATCGT", "GGACATCA", "AAGACCGT", "TTGCGAGA", "GCAATTCC", "GAATCCGT", "CCGCTTAA", "TACCTGCA"],
          ["ATAACGCC", "GAATCACC", "GGCAAGTT", "GATCTTGC", "CAATGCGA", "GGTGTACA", "CAGGTTCA", "GAACGAAG", "CTCAGAAG", "CATGAGCA", "GACGAACT", "AGACGCTA"],
          ["GCCTTAAC", "GTAAGGTG", "AGCTACCA", "CTTCACTG", "GGTTGAAC", "GATAGCCA", "TAGGAGCT", "CGAATTGC", "GTCCTAAG", "CTTAGGAC", "TCCACGTT", "CAACACAG"],
          ["GGTATAGG", "CGAGAGAA", "CAGCATAC", "CTCGACTT", "CTTCGGTT", "CCACAACA", "TACTCCAG", "GGAAGAGA", "GCGTTAGA", "ATCTGACC", "AACCAGAG", "GTACCACA"]
        ],
        "i7":[
          ["TTACCGAC", "AGTGACCT", "TCGGATTC", "CAAGGTAC", "TCCTCATG", "GTCAGTCA", "CGAATACG", "TCTAGGAG", "CGCAACTA", "CGTATCTC", "GTACACCT", "CGGCATTA"],
          ["TCGTCTGA", "AGCCTATC", "CTGTACCA", "AGACCTTG", "AGGATAGC", "CCTTCCAT", "GTCCTTGA", "TGCGTAAC", "CACAGACT", "TTACGTGC", "CCAAGGTT", "CACGCAAT"],
          ["TTCCAGGT", "TCATCTCC", "GAGAGTAC", "GTCGTTAC", "GGAGGAAT", "AGGAACAC", "CAGTGCTT", "CTTGCTAG", "TGGAAGCA", "AGCTAAGC", "GAACGGTT", "GGAATGTC"],
          ["TACGGTCT", "CCAGTATC", "TCTACGCA", "GTAACCGA", "GACGTCAT", "CTTACAGC", "TCCATTGC", "AGCGAGAT", "CAATAGCC", "AAGACACC", "CCAGTTGA", "TGGTGAAG"],
          ["AAGACCGT", "TTGCGAGA", "GCAATTCC", "GAATCCGT", "CCGCTTAA", "TACCTGCA", "GTCGATTG", "TATGGCAC", "CTCGAACA", "CAACTCCA", "GTCATCGT", "GGACATCA"],
          ["CAGGTTCA", "GAACGAAG", "CTCAGAAG", "CATGAGCA", "GACGAACT", "AGACGCTA", "ATAACGCC", "GAATCACC", "GGCAAGTT", "GATCTTGC", "CAATGCGA", "GGTGTACA"],
          ["TAGGAGCT", "CGAATTGC", "GTCCTAAG", "CTTAGGAC", "TCCACGTT", "CAACACAG", "GCCTTAAC", "GTAAGGTG", "AGCTACCA", "CTTCACTG", "GGTTGAAC", "GATAGCCA"],
          ["TACTCCAG", "GGAAGAGA", "GCGTTAGA", "ATCTGACC", "AACCAGAG", "GTACCACA", "GGTATAGG", "CGAGAGAA", "CAGCATAC", "CTCGACTT", "CTTCGGTT", "CCACAACA"]
        ]
      },
      // set B
      {
        "i5":[
          ["AAGCGACT", "ACGAATCC", "ATTACCCA", "CACTGTAG", "TCCCACGA", "AAGGAAGG", "AGGTAGGA", "ATGGCTGT", "CCTGTCAA", "TGTTCGCC", "ACCGGAGT", "TTCAATAG"],
          ["TGATAGGC", "GTCTGAGT", "GACTTGTG", "GTGCACGA", "ACCAACAG", "GCACACAA", "TCGCGCAA", "AAGGCGTA", "CCATCCGC", "ACAAGGCA", "CTTGACGA", "GTTTGCTC"],
          ["TCAGCGCC", "GGTGTGAG", "ACGAGGAG", "CTCGAAAT", "GTCAGTAT", "CCTCGGGT", "ATGTTCCT", "AACACCAC", "CCTAAACT", "CAGGTAAG", "AGAAGCCT", "GCCACGAC"],
          ["AGTCACAT", "CTTGCATA", "TAATCTCG", "CTCACAAC", "ATTCGAGC", "TAGCACCT", "CATTATGG", "ACCTCTTC", "TGTCACAC", "AAGGAGAC", "CTAGGTTG", "TCTGGAAC"],
          ["CCTTTCAC", "GCCAATCC", "TACGGCAG", "GTAACCAC", "CACCTGTA", "TGAGGACT", "TCTTGTTT", "GTCCGATC", "GATATGAA", "AGTCAGGT", "TGTGTCAG", "CACTAGAC"],
          ["CTTTCCCT", "ATGCCGGT", "TGCCCATC", "CATATCCA", "CCGACTCT", "TTCCCGAA", "GGCTTACT", "GAGGACCA", "AAGTGTGG", "ACCGTAAG", "AGAACCAG", "TTGCGTTA"],
          ["GACAATTC", "CATACCGT", "CAGCAGTC", "CGCTAATC", "TTGCTGGA", "GAGTCGAT", "ACGATATG", "CGCTCTTA", "GTTGGCGT", "TATGACGT", "ATTGGACA", "CCTATGCA"],
          ["ACACGACT", "ATCAGAGC", "TACCGGCT", "CTTCCAAC", "CAGCTTCG", "TACCTGTG", "ATCCGCAG", "CTGAGCTC", "TAGCTGGC", "TTGGGTAC", "ACCCGTTG", "CAACCGAG"]
        ],
        "i7":[
          ["CACTGTAG", "AAGCGACT", "ACGAATCC", "ATTACCCA", "TTCAATAG", "ACCGGAGT", "TGTTCGCC", "CCTGTCAA", "ATGGCTGT", "AGGTAGGA", "AAGGAAGG", "TCCCACGA"],
          ["GTGCACGA", "TGATAGGC", "GTCTGAGT", "GACTTGTG", "GTTTGCTC", "CTTGACGA", "ACAAGGCA", "CCATCCGC", "AAGGCGTA", "TCGCGCAA", "GCACACAA", "ACCAACAG"],
          ["ATGTTCCT", "AACACCAC", "CCTAAACT", "CAGGTAAG", "AGAAGCCT", "GCCACGAC", "TCAGCGCC", "GGTGTGAG", "ACGAGGAG", "CTCGAAAT", "GTCAGTAT", "CCTCGGGT"],
          ["CATTATGG", "ACCTCTTC", "TGTCACAC", "AAGGAGAC", "CTAGGTTG", "TCTGGAAC", "AGTCACAT", "CTTGCATA", "TAATCTCG", "CTCACAAC", "ATTCGAGC", "TAGCACCT"],
          ["TCTTGTTT", "GTCCGATC", "GATATGAA", "AGTCAGGT", "TGTGTCAG", "CACTAGAC", "CCTTTCAC", "GCCAATCC", "TACGGCAG", "GTAACCAC", "CACCTGTA", "TGAGGACT"],
          ["GGCTTACT", "GAGGACCA", "AAGTGTGG", "ACCGTAAG", "AGAACCAG", "TTGCGTTA", "CTTTCCCT", "ATGCCGGT", "TGCCCATC", "CATATCCA", "CCGACTCT", "TTCCCGAA"],
          ["ACGATATG", "CGCTCTTA", "GTTGGCGT", "TATGACGT", "ATTGGACA", "CCTATGCA", "GACAATTC", "CATACCGT", "CAGCAGTC", "CGCTAATC", "TTGCTGGA", "GAGTCGAT"],
          ["ATCCGCAG", "CTGAGCTC", "TAGCTGGC", "TTGGGTAC", "ACCCGTTG", "CAACCGAG", "ACACGACT", "ATCAGAGC", "TACCGGCT", "CTTCCAAC", "CAGCTTCG", "TACCTGTG"]
        ]
      },
      // set C
      {
        "i5":[
          ["AAAGCTAA", "ACCCTGAC", "ACGACGTC", "ACGTCGAG", "ACGTGAAC", "TATACCTC", "TGTCGTAG", "GCGCTAAT", "TTGTTGCA", "TTTCTCTA", "TTTGGGAT", "TAGTCACA"],
          ["TGGAGATT", "GTTGAAGG", "GTATGACG", "TGACTAGA", "TTCCCTTT", "CTCTTGAT", "CAATCATA", "AGAGCTGC", "CCACACTT", "CCAGCGAT", "CACCAAGC", "AGAAGTGG"],
          ["AATTAGAC", "GCACGGGA", "TACAGCAA", "TAGACGGG", "GACGCTCG", "ACTCTTAG", "GTTCTTAT", "CATACTTA", "CCCGTTTG", "TGGGAGTG", "CGGAGAGG", "CGTGGATT"],
          ["ACTTTGGG", "CGTATAAA", "CAGCAGGG", "CTCTTCTA", "CTCACGTC", "GAGCAACA", "GATGCGAC", "TTGCACCG", "ATGCTCCC", "CCCTCGTA", "TATTTACC", "GTAGATGC"],
          ["CGGACGGA", "AGAGACGG", "GATAAATG", "TACGTCCC", "CTGCCAAG", "CAGTGACG", "GAAGAGGG", "GCGGGATA", "GCTCAATA", "CGATATGG", "TATATGGA", "TACCGCTC"],
          ["GCAGAGCC", "TACAAGTC", "GCATCAAG", "GATGGAAA", "ACGCCGCA", "AAGATTGA", "TAGTAATC", "GAAGTGAA", "GTAGTTCG", "TTGTGCCC", "GTTAACAT", "CGAACCAC"],
          ["GCATGATC", "TGAATCTT", "CGATACAT", "GTTCGTCG", "CGCCAGTC", "GTGTGTTT", "GTGTGGAG", "CTGTTTAC", "CGAGAACC", "TGTCCTCT", "CGTCTTGG", "TATTGTTC"],
          ["TCGACCTA", "GCAACTTG", "AACCCTAT", "GAGACCAA", "CTAAACAA", "CGTCCGAC", "ACGTTGTA", "GAGCACTC", "GCCATGTA", "GTATAGTC", "CGTAGCGA", "GTTGTGTG"]
        ],
        "i7":[
          ["TGTCGTAG", "GCGCTAAT", "TTGTTGCA", "TTTCTCTA", "TTTGGGAT", "TAGTCACA", "AAAGCTAA", "ACCCTGAC", "ACGACGTC", "ACGTCGAG", "ACGTGAAC", "TATACCTC"],
          ["CAATCATA", "AGAGCTGC", "CCACACTT", "CCAGCGAT", "CACCAAGC", "AGAAGTGG", "TGGAGATT", "GTTGAAGG", "GTATGACG", "TGACTAGA", "TTCCCTTT", "CTCTTGAT"],
          ["GTTCTTAT", "CATACTTA", "CCCGTTTG", "TGGGAGTG", "CGGAGAGG", "CGTGGATT", "AATTAGAC", "GCACGGGA", "TACAGCAA", "TAGACGGG", "GACGCTCG", "ACTCTTAG"],
          ["GATGCGAC", "TTGCACCG", "ATGCTCCC", "CCCTCGTA", "TATTTACC", "GTAGATGC", "ACTTTGGG", "CGTATAAA", "CAGCAGGG", "CTCTTCTA", "CTCACGTC", "GAGCAACA"],
          ["GAAGAGGG", "GCGGGATA", "GCTCAATA", "CGATATGG", "TATATGGA", "TACCGCTC", "CGGACGGA", "AGAGACGG", "GATAAATG", "TACGTCCC", "CTGCCAAG", "CAGTGACG"],
          ["TAGTAATC", "GAAGTGAA", "GTAGTTCG", "TTGTGCCC", "GTTAACAT", "CGAACCAC", "GCAGAGCC", "TACAAGTC", "GCATCAAG", "GATGGAAA", "ACGCCGCA", "AAGATTGA"],
          ["GTGTGGAG", "CTGTTTAC", "CGAGAACC", "TGTCCTCT", "CGTCTTGG", "TATTGTTC", "GCATGATC", "TGAATCTT", "CGATACAT", "GTTCGTCG", "CGCCAGTC", "GTGTGTTT"],
          ["ACGTTGTA", "GAGCACTC", "GCCATGTA", "GTATAGTC", "CGTAGCGA", "GTTGTGTG", "TCGACCTA", "GCAACTTG", "AACCCTAT", "GAGACCAA", "CTAAACAA", "CGTCCGAC"]
        ]
      },
      // set D
      {
        "i5":[
          ["AGTCCCGG", "AGTCTGCT", "AGTACAAG", "AGTTGGAT", "GTTGCCTT", "TATCAGTA", "ACTTCTGC", "AGCCTGGA", "GCAATGGG", "GACATTAA", "AAAGATCG", "AGTAGTAA"],
          ["TCCTGGAC", "GCCGAATC", "TACTGTGA", "TAACACGC", "CCAATGAA", "CGAGTCAG", "TTAAGCAG", "GAGGACAG", "CTGGACAC", "ATGTACGT", "GTGAGCTA", "TACTAAGG"],
          ["CTACATGA", "ACTATGAT", "CCGGAATT", "AGACTCAC", "ATCAGTTG", "TTTCCATC", "ATCAAATC", "CTATCGAA", "AAGTATGC", "ATGACAAA", "AACGCGGG", "CATTCGGA"],
          ["CCGGATAG", "CCCTATCT", "TCGCTCGG", "CAGAGTGT", "ACATACAC", "CTTTAACT", "TTTGAGTC", "TCACTAAC", "TCCGATGG", "CCACCTAC", "CTTGTGCT", "AATCGTCA"],
          ["AACCCGCC", "CGTTGTCC", "AGTGCGGA", "ACATTACG", "CTCCATAT", "GCCTCTAT", "AAATCCTC", "TCGATAAG", "GACAACGG", "TGCTGTTG", "GCTTACCC", "GCTGATTT"],
          ["CGAACGTG", "TGGAACGG", "GCTTCACA", "ATTACTAC", "GCTTAAGT", "CCTCCTTT", "TACAGATG", "CTTTATTC", "TAGCTTTA", "CATTTCAG", "AGTAAACA", "CGCGAAAG"],
          ["CCGTAGAA", "CCCTTCGG", "CCGATCGT", "TGGACCCT", "ACACGTAT", "CAGTTCCC", "TAAGCGCA", "CTGCCTTC", "AAACAGTC", "CGTCCCTA", "CGATGTAA", "TTGCCACT"],
          ["CATCTACT", "TGTCCAAA", "CCGTAAGC", "CGCTTGCA", "CAAGAAGT", "TACCTTGT", "CAACGGAA", "ACAACCAA", "ACCTCACT", "TACGATTA", "CCTAGTCG", "TTCGTGGA"]
        ],
        "i7":[
          ["ACTTCTGC", "AGCCTGGA", "GCAATGGG", "GACATTAA", "AAAGATCG", "AGTAGTAA", "AGTCCCGG", "AGTCTGCT", "AGTACAAG", "AGTTGGAT", "GTTGCCTT", "TATCAGTA"],
          ["TTAAGCAG", "GAGGACAG", "CTGGACAC", "ATGTACGT", "GTGAGCTA", "TACTAAGG", "TCCTGGAC", "GCCGAATC", "TACTGTGA", "TAACACGC", "CCAATGAA", "CGAGTCAG"],
          ["ATCAAATC", "CTATCGAA", "AAGTATGC", "ATGACAAA", "AACGCGGG", "CATTCGGA", "CTACATGA", "ACTATGAT", "CCGGAATT", "AGACTCAC", "ATCAGTTG", "TTTCCATC"],
          ["TTTGAGTC", "TCACTAAC", "TCCGATGG", "CCACCTAC", "CTTGTGCT", "AATCGTCA", "CCGGATAG", "CCCTATCT", "TCGCTCGG", "CAGAGTGT", "ACATACAC", "CTTTAACT"],
          ["AAATCCTC", "TCGATAAG", "GACAACGG", "TGCTGTTG", "GCTTACCC", "GCTGATTT", "AACCCGCC", "CGTTGTCC", "AGTGCGGA", "ACATTACG", "CTCCATAT", "GCCTCTAT"],
          ["TACAGATG", "CTTTATTC", "TAGCTTTA", "CATTTCAG", "AGTAAACA", "CGCGAAAG", "CGAACGTG", "TGGAACGG", "GCTTCACA", "ATTACTAC", "GCTTAAGT", "CCTCCTTT"],
          ["TAAGCGCA", "CTGCCTTC", "AAACAGTC", "CGTCCCTA", "CGATGTAA", "TTGCCACT", "CCGTAGAA", "CCCTTCGG", "CCGATCGT", "TGGACCCT", "ACACGTAT", "CAGTTCCC"],
          ["CAACGGAA", "ACAACCAA", "ACCTCACT", "TACGATTA", "CCTAGTCG", "TTCGTGGA", "CATCTACT", "TGTCCAAA", "CCGTAAGC", "CGCTTGCA", "CAAGAAGT", "TACCTTGT"]
        ]
      }
    ],
    "IndexNamingRule": {"i5": function(plate, row, col){let n = ('000' + (96*plate+col*8+row+1)).slice(-3); return "NEBUDI"+n+"_i5"},
                        "i7": function(plate, row, col){let n = ('000' + (96*plate+col*8+row+1)).slice(-3); return "NEBUDI"+n+"_i7"}
                    }
  }
