INDEX_DATA["NexteraXTv2"] = {
    "kitName": "NexteraXT v2",
    "indexSetNames":["Set A", "Set B","Set C","Set D"],
    "defaultReadLength": 151,
    "indexLength": 8,
    "trimTarget1": "CTGTCTCTTATACACATCT",
    "trimTarget2": "CTGTCTCTTATACACATCT",
    "adapterExtra1": "ATCTCG",
    "adapterExtra2": "GTGTAG",
    "indexSeq":[
      // set A
        {"i5":[
          ["ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG"],
          ["AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA"],
          ["CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC"],
          ["TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT"],
          ["TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT"],
          ["AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG"],
          ["ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG"],
          ["CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA"]
        ],
        "i7":[
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"]
       ]
     },
     // set B
     {"i5":[
          ["ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG", "ATAGAGAG"],
          ["AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA", "AGAGGATA"],
          ["CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC", "CTCCTTAC"],
          ["TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT", "TATGCAGT"],
          ["TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT", "TACTCCTT"],
          ["AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG", "AGGCTTAG"],
          ["ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG", "ATTAGACG"],
          ["CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA", "CGGAGAGA"]
       ],
       "i7":[
          ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
          ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
          ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
          ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
          ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
          ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
          ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
          ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"]
      ]
    },
    // set C
      {"i5":[
          ["CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA"],
          ["AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA"],
          ["ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG"],
          ["TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC"],
          ["CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG"],
          ["ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT"],
          ["TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC"],
          ["TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA"]
        ],
        "i7":[
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"],
          ["TAAGGCGA", "CGTACTAG", "AGGCAGAA", "TCCTGAGC", "GGACTCCT", "TAGGCATG", "CTCTCTAC", "CGAGGCTG", "AAGAGGCA", "GTAGAGGA", "GCTCATGA", "ATCTCAGG"]
       ]
     },
     // set D
     {"i5":[
         ["CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA", "CTAGTCGA"],
         ["AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA", "AGCTAGAA"],
         ["ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG", "ACTCTAGG"],
         ["TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC", "TCTTACGC"],
         ["CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG", "CTTAATAG"],
         ["ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT", "ATAGCCTT"],
         ["TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC", "TAAGGCTC"],
         ["TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA", "TCGCATAA"]
       ],
       "i7":[
         ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
         ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
         ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
         ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
         ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
         ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
         ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"],
         ["ACTCGCTA", "GGAGCTAC", "GCGTAGTA", "CGGAGCCT", "TACGCTGC", "ATGCGCAG", "TAGCGCTC", "ACTGAGCG", "CCTAAGAC", "CGATCAGT", "TGCAGCTA", "TCGACGTC"]
       ]
      }
  ],
   "IndexNamingRule": {"i5": function(plate, row, col){
                               let index_no = [
                                  [ 2, 3, 5, 6, 7, 8,10,11],
                                  [ 2, 3, 5, 6, 7, 8,10,11],
                                  [13,15,16,17,18,20,21,22],
                                  [13,15,16,17,18,20,21,22]
                                ];
                               let n = ('00' + index_no[plate][row]).slice(-2);
                               return "S5" + n;},
                      "i7": function(plate, row, col){
                               let index_no = [
                                 [ 1, 2, 3, 4, 5, 6, 7,10,11,12,14,15],
                                 [16,18,19,20,21,22,23,24,26,27,28,29],
                                 [ 1, 2, 3, 4, 5, 6, 7,10,11,12,14,15],
                                 [16,18,19,20,21,22,23,24,26,27,28,29]
                               ];
                               let n = ('00' + index_no[plate][col]).slice(-2);
                               return "N7" + n;}
                   }
  }
