INDEX_DATA["qiagenUDI"] = {
    "kitName": "QiaSeqFX UDI",
    "indexSetNames":["Set A", "Set B", "Set C", "Set D"],
    "defaultReadLength": 151,
    "indexLength": 10,
    "trimTarget1": "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA",
    "trimTarget2": "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT",
    "adapterExtra1": "ATCTCG",
    "adapterExtra2": "GTGTAG",
    "indexSeq":[
      // set A
      {
        "i5":[
          ["AGTCGGCCAT", "GAAGGTGCCT", "TGTTATGGCT", "TCCAAGAATG", "AACGACTGGC", "CCAGAATTCT", "CCTTCTACAA", "ACCTTAGACG", "CTAACGAGCG", "GAATCTCAAC", "TCCATTCCAT", "TGGAGTACAA"],
          ["GTGCTCATCG", "TTACCAACAG", "CCACTTGTGG", "AACCTTGCAT", "CGACAAGGCA", "AGAGTCAATG", "TAGTGCTAGG", "TGTTCACCTC", "CAGCGTTGTT", "TCCGCACACA", "GTGAGGAATG", "TTATGTGCAC"],
          ["TCGACTTATC", "AGGTACCAGC", "GTGTGATAAC", "TTGTCTGGCG", "CAGCGGATAG", "TTGAAGCCGC", "AGAACACGAT", "GTAGTTCTGA", "AATAGCCGCG", "TTCGCCGAAC", "CTTCCTATGC", "TACTTGTCCT"],
          ["CAAGGCGTGA", "CCGCTCCTTA", "AAGAACGGTA", "GCCAACCTTC", "TTCCGGCATT", "GAGACCATAA", "GATAAGTTGG", "TCAATATCCG", "TGTGTCGAGC", "CAATACAGCT", "AACACGAACA", "CTCGAATCGG"],
          ["TTGTGTTCCT", "TGGAGCGATT", "CCTAACGCCT", "CGTGATGCGA", "CGGATAACCG", "CCTGGTTACG", "CCTTGGCTTC", "ATCTACTCCT", "GTTGGAAGAA", "TCATCCGCTG", "AACGGTCTTA", "AAGTTCCTAC"],
          ["GCCTACTGAG", "CAATTAGGAG", "GACGTTACGG", "TCATGACCGG", "ACTCTTCCGC", "TATCTGAGCT", "TTGAACTCCA", "TATTCGGCGG", "CAACCGCCAA", "ATCCAAGGAC", "CTGGTACCAT", "TCGTAGTGTA"],
          ["CAGGCACTTC", "ATTATGAGGC", "TGGCTATTAC", "GCTTGTGAAT", "GACTAACCAA", "GTAACACCGG", "AGGATTGAAG", "GTATAGACTC", "ATTGCCTGTT", "AGCATCTAGA", "AAGCTGTCGG", "TCAAGGTCAT"],
          ["AGGCGAGAGA", "GCTCAATACA", "ATCGGCGCTA", "TTACAGGTTG", "TCACACTGAA", "AGGTTAGGTC", "CACGCAAGAT", "CCGGTAATAA", "CGCCATTCTG", "ATGTGGCTCG", "TCATATCGTC", "CGTCACGTAG"]
        ],
        "i7":[
          ["TGAACGTTGT", "GAGCCAAGTT", "TGCATAGCTT", "CACTGCTATT", "GATTGAGTTC", "AGGCCTACAT", "AGGATGTCCA", "CCTCGGAATG", "ATGACTCGAA", "ACGTTGACTC", "CCTCCATTAA", "CTGATGATCT"],
          ["ACCAGACTTG", "AAGGCCGTAG", "AACCTTCTCG", "AATGGTAGGT", "GTAATGCCAA", "TGTGGAACCG", "CACCTTATGT", "GTTCTGGAAC", "GAACAATCCT", "CCACTTAACA", "AGTCGCGGTT", "ACTAGGTGTT"],
          ["ACTGGCGAAC", "TTAGAGAAGC", "AAGAGATCAC", "GATACCTATG", "TCGTTGCGCT", "CGTATTAAGC", "AAGCGGCTGT", "AGATTCACCA", "TGGCAAGGAG", "AGCAGTTCCT", "CTCATCCAGG", "CTGTTAGCGG"],
          ["GCGTTAGGCA", "TCTAAGACCA", "GCCTGAAGGA", "CACTAGGTAC", "AGGTGAGTAT", "CCAGTGGTTA", "TTCCTGTGAG", "TCGGTCAGAT", "GAATATTGGC", "TCGCCTTCGT", "TGTGGTTGAA", "ATCGCACCAA"],
          ["TTATCGGCCT", "TGTAACCACT", "ATTGTGCCTT", "AGCTCGTTCA", "TCGATAATGG", "GCGTTCGAGT", "AGTACAGTTC", "CACTCTCGCT", "CCGGAACCTA", "TAGGACTGCG", "TTATGCGTGG", "CTTACTTGGT"],
          ["GAGGTATAAG", "CCGACACAAG", "TCCTCTACCG", "TGTCAGTCTT", "GCGTCTCTTC", "CCTTCCGGTT", "TACAGCCTCA", "GTTGGTCCAG", "ACTTGTTCGG", "TCCGAGCGAA", "GCGAATGTAT", "CCTTAATGCG"],
          ["TCAAGGATTC", "CTCTGATGGC", "TACCATGAAC", "GATGAACAGT", "GTCTCCTGCA", "CACAAGACGG", "GTTCTATTGG", "AGCTCGAAGC", "CAAGTCCAAT", "TTCGGTTGTT", "GTCAAGCTCG", "TCTCGCCTAG"],
          ["CGAACCGAGA", "CGGCCTGTTA", "CATTGGCAGA", "ACAATCGGCG", "GAGCTTCATT", "GCTTACACAC", "ATATACCGGT", "AGAGGTTCTA", "AACCGCAAGG", "ACAGGAGGAA", "TAGAGTTGGA", "TCTTCAGAGA"]
        ]
      },
      // set B
      {
        "i5":[
          ["CCTGATTGTT", "CATAGTGGCT", "ACCATGGCCT", "TATCGCACTT", "TTCTCCACGC", "TTCAATCGCT", "CTCGTGTTAA", "AATTAAGCCG", "CTTCGAGGAG", "ACCGCCTTAC", "TCCTAAGGTT", "GTCGACGGAA"],
          ["TGCACACCAG", "TGGTAGGTGG", "TTGGCCAATG", "CGTGTAGCCT", "AGGAGGCGTA", "AGAGAGGTAG", "TCTAGAGGCG", "CCTGCAACTC", "TCTGCGGTAT", "CGACCTTGAA", "GAGTTGCCAG", "TGGCATCTCG"],
          ["AAGGATATGC", "ACACCGGAAC", "GATTCATAGC", "GCCGATATAG", "CTACCGAATT", "GACAGTTGTC", "AAGGTCGATT", "TGTTCGTGGA", "ATCAGATAGG", "TACTCGGATA", "CAACAAGTTC", "GCACGAACTT"],
          ["GTACAGGACA", "GTCAGACCTA", "CGAGGACCAA", "TTACCTTAGC", "GTTCGACAAT", "CCGCAATGGA", "GTTATTGCGG", "TCCTCCGTCA", "GTAACCGATC", "TAAGCGCGCT", "ATCTTGCACA", "CTTATGGACG"],
          ["GCGACGTTCT", "AATGCTTCCT", "GTATGTCGCT", "AACCAGGTTA", "CGCAAGGTTG", "TTGCGAGGCT", "TCGTTGGAAC", "CGTACTCATT", "CACCTCACCA", "ATGTCTCCGG", "TCTCTCGATT", "TATGCCACAA"],
          ["CTAGTCCGTG", "CCAACTAAGG", "AGACTACTTG", "TAGACCAACT", "TACGCAGTGC", "AGCCTGTATT", "CGGTCTAACA", "TCGGAAGACG", "TACGCCGGTT", "CAGTTATCTC", "CTGACACGCT", "ATTCCGATCT"],
          ["AGTGTTCAAC", "TGAATAGGAC", "TCTTCTTGAC", "CCAGCTGCAT", "ACTACTAGCA", "TAACGGTCCG", "CTATGAGGTT", "AATCTCTGTC", "GATCGGTATT", "GCGCTTACAA", "AATCACCAAG", "CAGTAGAATG"],
          ["TACCACGCGA", "GTCCATCTTA", "CATAACAGGA", "GAAGGCAACG", "TCCGTGACTT", "GCATAAGCGC", "GTGGATTCAT", "GTTAGCGTAA", "TTGAGTATCG", "CCTCCTCTTG", "TTGCTGCTTC", "CTACGGCGAT"]
        ],
        "i7":[
          ["TACCGGTGGT", "GCTCTTGCCT", "CCTTACCAAT", "GTACCTTGTT", "GAATGGAAGC", "AAGAGGAGAT", "AAGCGTACCA", "GACAATAACG", "AAGACCTCTT", "GACGAAGGTC", "CACTGAACCG", "TGAGTGTGTT"],
          ["AGGTGTTACG", "AATCTTGAGG", "TTAATCCTCG", "GAGTGCCTCT", "GTTCTCCATA", "GTCTTCTCGG", "TCATGTTGGT", "ACAGTTAAGC", "GACCTCTTCT", "ATCACCGTGA", "TACTGTGTGA", "TAGTTAGTCG"],
          ["ACAGACCGAC", "CTTAACGGTC", "TTCCGAGTTC", "TAAGTAGCGG", "GTCACTATGT", "GAAGCCACTC", "TTGGAATGGT", "AGCCACACTA", "TACTTCCTTG", "GCTACAGTGT", "GCATTCTGTT", "GCCTGATCCT"],
          ["CGAATACGTA", "TTGTGACCAA", "CTCGAGAGGA", "CGTGGTGTTC", "TGGTAGAACT", "GTAGGACACA", "GTGTATGTTG", "CAATCGTCTT", "TGCGATACGC", "CGTCGAATAT", "CTCCGCTAAG", "CGAGTACAGG"],
          ["TAGCATCGAT", "TCACACACCT", "TGTTGGCTGT", "CATTCCTGAA", "ACGCCTATGG", "CTCCTCGTAT", "TCCTGTCAAC", "AGGAGCTTGT", "GCAGGCTTAA", "CAACCATCGG", "TCGCTTGAGA", "GCCTAGATTA"],
          ["CCATGAGTCG", "CTGCAATTAG", "CGTATCTGCG", "AAGATGCATG", "AATCCGTTAC", "CCACATGATT", "TAATCAGGCA", "TTGAGCGGAG", "TAAGCTTGTG", "CGGTCCATTC", "AACTAGCCTT", "TCGGCACTGT"],
          ["ACTAACATGC", "CTCCTTACTC", "CCATAGTATC", "CCTTGGAGCT", "GTTGAGGCTA", "AGACGGTTGG", "GTAGTGGATT", "AGTAGCTCTC", "ATGGTCCGCT", "AGAAGAGCCA", "TTCGCTCAGG", "CCGTGCAAGA"],
          ["ACACTCTCTA", "GCAACGCAGA", "TGGACAGTAA", "ACCGGAACAG", "TATCAACTGG", "CTAGGTTGAC", "AATTGCGCAT", "CACGCTGTCA", "ATGTCAGAAG", "CTATGCAATG", "CTCTACAACA", "CTGGCTGGTT"]
        ]
      },
      // set C
      {
        "i5":[
          ["GTGTAAGGAT", "AGCGGACGTT", "GCCACCTAAT", "AACACTGTTG", "GCAATACTAC", "CCGTTCTCCT", "ACCAACAGAA", "TGAGAGCCTG", "TGCCACCGTT", "AGATGCCTTC", "CTCTTGTGTT", "CGGAAGTTAC"],
          ["AGTCCTTGCG", "GACATGTGCG", "TTCTTGATCG", "TTCCTCTCTT", "ATCCGCTGGA", "GTCTAACAGG", "CCTGACGATG", "GAGAGCGAAC", "ACACCGTCCT", "GCAGTAGAGA", "ACCGATTGCG", "TAGTCGTGAG"],
          ["TAACGCCAGC", "TCAGGTGTGC", "AGAAGACAGC", "GCTACAACCG", "GAGGTGGTTG", "AACGTAGAAC", "CTTCATGCAT", "ATTAGTCCGA", "CAGGTCACAG", "TTGTTCGGTT", "TCTACGCAAC", "GCCGTTGGTT"],
          ["CCTCTAAGTA", "CTCTGGACAA", "CAGACATGTA", "CACTTCAGGC", "CGCCTAAGCT", "TGTGGACTTA", "GCGATTCACG", "GAAGATCTCG", "TTGTTACAGC", "GTGGCGAGAT", "GATCACTCTA", "TACAGGCAGG"],
          ["GCATCGCCAT", "CAGGAAGGCT", "TCAACTGGTT", "AGTGTCGTAA", "AAGGAACCGG", "ATGGTTCTTG", "AAGGCTGCTC", "GTCCGGTTAT", "GACGTCCGTA", "CGTTGCATGG", "GCTGCGTCTT", "CTGCAGCGTA"],
          ["CGCACCAATG", "TGGCGTAAGG", "AGCTTACCGG", "GATCTAGGCG", "GTTCAATGTC", "GTCATCAACT", "TGGTAATCGA", "TAACTACACG", "GCTCCTTAGG", "TACACCATTC", "TCGAGAAGTT", "TCGCAACATT"],
          ["TATATCTCGC", "GTACGTATTC", "CTATTCGAAC", "CATCCAGATT", "TCGCCTCTAA", "CAAGAGTAGG", "AATTGGACTG", "ACCTATGTTC", "CTGGCCTTAT", "ACGGCATATA", "CTCAGTTGCG", "CAGAACGTCG"],
          ["ATAGCAGTCA", "ACGGTGCCAA", "GAGCCTGACA", "TGTACCGTCG", "GTTCGGCTTG", "TGGATTGTTC", "CCAAGCCTCT", "CGATGTTAGA", "TACAGATGAG", "ATCTATCGAG", "ATTGCGGAGC", "GTGTCCTATT"]
        ],
        "i7":[
          ["CGTTAGGATT", "ACGTCTTGTT", "TCAGCCTATT", "TGTTCCTCAT", "GTTGTCTTAC", "CCAAGTAGAT", "CTCTTATCCA", "GAACCGGTAG", "CACCACTCAT", "CAACGTACGC", "TCCTGGAAGT", "CCGTTAAGGT"],
          ["TTCCATTACG", "ATGAAGTGCG", "GTTGTGAGCG", "CATACCTTCT", "GTGGCAACTA", "AAGGTTGGCG", "TCACAGCGGT", "AGCAATGAGC", "CTTCGTAACT", "AGCTCAGGAA", "GCATTGTTAG", "TGCTGAGAGG"],
          ["TAGCGGTAAC", "CGATCACTGC", "TCAGTAACAC", "GCCTTCAATG", "GAGCAGGCAT", "TGCTCTGGTC", "CCTCTGTCGT", "CAAGACTCCA", "CAGTATTCGG", "GATAGGCGGT", "GACCTACAGC", "TTGTCACTTG"],
          ["GTAGCCAGGA", "CCTATCGGAA", "AAGGCTCAGA", "CTTGACCAGC", "AACGGCACCT", "ACTGTAACGA", "TCTGTTCTCG", "ACCGTGTAGG", "CAGTCTGGAC", "AGTAGGAAGT", "CACCGACGTA", "GCTGTTATGT"],
          ["AGGATACTCT", "CAGAGAGCTT", "GTGTGGTGGT", "CTACACACAA", "AGTAACCTTG", "GATTCCAGGT", "GATACTTCAC", "AGGCACAGGT", "TACCGTTCTA", "CATGTTGTAG", "CTCTCACCTT", "GCAGCAGTTG"],
          ["TATCCTCCAG", "GCAACTTGCG", "CCGAGCTTAG", "TAGGCTGAAT", "TCTCATAAGC", "TTCACCAGAT", "AGTGCTGATA", "CGACAGATCG", "GTGTCCACAG", "CACATTCTTC", "CTCGTTCATT", "GCAGATCAAT"],
          ["TAAGTCGTTC", "TATGGAGGAC", "ATCACGCTTC", "TCGGAGTCCT", "TGCTTGCCAA", "ACTTCCAAGG", "ATCCTTCGGT", "ACGCGACAAC", "TTACGACTGT", "GCAGCTCGTA", "TGGTGGCAAG", "TGGTTCACGG"],
          ["TCCGGATTGA", "TGAGATCAGA", "TAGCTATGCA", "AACATCGCGG", "CGGTTCCTGT", "CCGAATATTC", "GACAACGATT", "ACTTGCGTTA", "GACGCGAATG", "GTTCAGACGG", "GATTGCTTGA", "TCGACCGCAT"]
        ]
      },
      // set D
      {
        "i5":[
          ["TGAGGCACAT", "CGCTCATAAT", "GCGTTACCTT", "ATGGACGAGG", "GAACTGCGTC", "CGGTTGGCAT", "CGTACATCCA", "GTACTCGAGG", "TGCTATCATG", "ACCTCCACAT", "TATGAGCCAT", "ACAAGCCATA"],
          ["AACGGAGTCG", "TTATAACGCG", "AGTAAGGCGG", "AACCAACGCT", "CCGAGTTCCA", "GAATCGACCG", "ACGCTGGTAG", "CCTCAGTGAC", "CGAAGCTGTT", "TGAGCCATGG", "CTTCACTCCG", "AGGAACAACG"],
          ["CCACAACAGC", "ACATGCACGC", "CTGCCTCAAC", "TGTTCGAATG", "ATTGGTGTGG", "ACTGTACTTC", "CTGAATCCTT", "TCTAACCGTA", "TAAGCACTAG", "GCGTGATTGG", "ACCATAGGTA", "CTAATGTCGG"],
          ["GTGATTGGTA", "GAGCCGCTTA", "TAGGTCGCCA", "GTCGGTAAGC", "GCCGAGAACT", "TTACTGCAGA", "ACACACCTCG", "ATTCTCGTTG", "ACGTATCACA", "CTGGATCTAA", "ACTGTCTCAT", "TGCCTTCACA"],
          ["CGTAAGACAT", "TCTCCATGTT", "TGTCGCTTCT", "CCTAAGCTAA", "CGTCGTCAAG", "GCTAGGATAG", "GAGCGTCTAC", "CCGGTGTATT", "ATACGCTCAT", "CGATATTCCT", "CAACTCTTAG", "AGACGATGCT"],
          ["TATTGTTGCG", "AGAGACTCGG", "GATTATCCTG", "TGTGTGTCGG", "TAGCGACCTC", "AAGGAGTGTT", "TGACGGACGA", "GATGGATCGG", "CCATATCTAG", "ACATAGGAGG", "CATACGGTTA", "TCCTAGTCGG"],
          ["GTCTTCGTTC", "GTAGAAGTAC", "CTGTAGGAGC", "ATCAGCGAAT", "ATGCTACTGA", "TTAGGTTCGG", "CCTATCACGG", "AGCGAGATTC", "CAGCATAGCG", "CGTGTCTCTA", "CATGGACTCT", "CGGTAATGTT"],
          ["ACGTCCTCGA", "CATGTGAACA", "ACCTGTTGAA", "TGCCTCTTGG", "TCCACGTTAG", "GCGACTAGAC", "AGGTCATCCT", "TTGCCGGTCA", "TCACGTAGTA", "ACTGAGCTGG", "TGCGGTCTAG", "ACGAATTAGG"]
        ],
        "i7":[
          ["TAACCTAGGT", "GTTAACTGCT", "AACTGTGGTT", "TATGTCCTGT", "CAAGCTGAGC", "CGGTGGTTCT", "TGACGCGTTA", "ATGACGGATT", "CTGTGCGACT", "CGCGTTATCG", "AAGCAGGACG", "GTCCATGAGT"],
          ["AACTCATGCG", "TCGGACCTTG", "ATTACCTCGG", "GCCAATTCGT", "CCAGAGCACA", "CTGTCGTTGG", "TACAGAACGT", "GTCTGAGTAG", "TCCGTATGCT", "GTAGCCTCCT", "ACGAGTCGGT", "ACTCCAGTCG"],
          ["CCGGATGAAC", "TGCAGCAAGC", "CGCTGTATAC", "TAGGCGATCG", "TGTACAAGGT", "TGATCGACAC", "CTTGTCAGGT", "TGCCAGATGT", "CCATCGATGT", "ACTAGACACT", "AGTGTACGCG", "TCTCAGCACG"],
          ["CGTTGCCGTA", "CACATGCGAA", "CTTGCTCACA", "ATGAGTGTAC", "TAGAATGCCT", "CCACCAGCTA", "ATCCACAGCG", "GCTAAGCATT", "GTGAGCCGTT", "CGATTCGTTG", "ACCGACCATT", "ATCGTGATGT"],
          ["GCTCTACGGT", "CAGACGTAAT", "CAACACCTGT", "CCGAAGGATA", "TGTCTTACTG", "CACGGTTCGT", "CCTATCCATC", "ACAGCATGGT", "TGCCGTTAAT", "GAAGAGATGT", "TTGCTAACGT", "ACGCAATCCG"],
          ["TGCATTGGCG", "ATTCGGTACG", "CAATTGCTCG", "AGTCCACTGT", "ATGACTAAGC", "AGTGAGAGCT", "ACCGCGAGTA", "ATAGAGACCG", "CGGATGTGGT", "AGATCCGACG", "CTTGATACTG", "GAGATCGGCT"],
          ["CGATTGTGAC", "TTAGCACGGC", "CATAGACAAC", "GCGGCTAATT", "ATGTAGGCAA", "TTGCATGCGG", "AAGTTCTGGT", "ATATCGCGTA", "TCGCGTGTTG", "CCAGGACATT", "CTGGATAAGT", "CTACGTCTCG"],
          ["GACTGCACTA", "GAGGATAGTA", "TTGGTGTCTA", "TCTAACTCAG", "GCGAAGAGGT", "TATACGTGTC", "ACAGGTATCG", "TTAAGGAGGT", "CCGCGATCAT", "ACGTGGCATT", "ATAGCTTACG", "CTCAGGCTGT"]
        ]
      }
    ],
    "IndexNamingRule": {"i5": function(plate, row, col){let n = ('000' + (96*plate+col*8+row+1)).slice(-3); return "UDI"+n+"_i5"},
                        "i7": function(plate, row, col){let n = ('000' + (96*plate+col*8+row+1)).slice(-3); return "UDI"+n+"_i7"}
                    }
  }
