INDEX_DATA['truSeqHT'] = {
    "kitName": "TruSeqHT / QiaSeqFX CD",
    "indexSetNames":['Index 1-96'],
    "defaultReadLength": 151,
    "indexLength": 8,
    "trimTarget1": "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA",
    "trimTarget2": "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT",
    "adapterExtra1": "ATCTCG",
    "adapterExtra2": "GTGTAG",
    "indexSeq":[
      {
        "i5":[
          ["AGGCTATA","AGGCTATA","AGGCTATA","AGGCTATA","AGGCTATA","AGGCTATA","AGGCTATA","AGGCTATA","AGGCTATA","AGGCTATA","AGGCTATA","AGGCTATA"],
          ["GCCTCTAT","GCCTCTAT","GCCTCTAT","GCCTCTAT","GCCTCTAT","GCCTCTAT","GCCTCTAT","GCCTCTAT","GCCTCTAT","GCCTCTAT","GCCTCTAT","GCCTCTAT"],
          ["AGGATAGG","AGGATAGG","AGGATAGG","AGGATAGG","AGGATAGG","AGGATAGG","AGGATAGG","AGGATAGG","AGGATAGG","AGGATAGG","AGGATAGG","AGGATAGG"],
          ["TCAGAGCC","TCAGAGCC","TCAGAGCC","TCAGAGCC","TCAGAGCC","TCAGAGCC","TCAGAGCC","TCAGAGCC","TCAGAGCC","TCAGAGCC","TCAGAGCC","TCAGAGCC"],
          ["CTTCGCCT","CTTCGCCT","CTTCGCCT","CTTCGCCT","CTTCGCCT","CTTCGCCT","CTTCGCCT","CTTCGCCT","CTTCGCCT","CTTCGCCT","CTTCGCCT","CTTCGCCT"],
          ["TAAGATTA","TAAGATTA","TAAGATTA","TAAGATTA","TAAGATTA","TAAGATTA","TAAGATTA","TAAGATTA","TAAGATTA","TAAGATTA","TAAGATTA","TAAGATTA"],
          ["ACGTCCTG","ACGTCCTG","ACGTCCTG","ACGTCCTG","ACGTCCTG","ACGTCCTG","ACGTCCTG","ACGTCCTG","ACGTCCTG","ACGTCCTG","ACGTCCTG","ACGTCCTG"],
          ["GTCAGTAC","GTCAGTAC","GTCAGTAC","GTCAGTAC","GTCAGTAC","GTCAGTAC","GTCAGTAC","GTCAGTAC","GTCAGTAC","GTCAGTAC","GTCAGTAC","GTCAGTAC"]
        ],
        "i7":[
          ["ATTACTCG","TCCGGAGA","CGCTCATT","GAGATTCC","ATTCAGAA","GAATTCGT","CTGAAGCT","TAATGCGC","CGGCTATG","TCCGCGAA","TCTCGCGC","AGCGATAG"],
          ["ATTACTCG","TCCGGAGA","CGCTCATT","GAGATTCC","ATTCAGAA","GAATTCGT","CTGAAGCT","TAATGCGC","CGGCTATG","TCCGCGAA","TCTCGCGC","AGCGATAG"],
          ["ATTACTCG","TCCGGAGA","CGCTCATT","GAGATTCC","ATTCAGAA","GAATTCGT","CTGAAGCT","TAATGCGC","CGGCTATG","TCCGCGAA","TCTCGCGC","AGCGATAG"],
          ["ATTACTCG","TCCGGAGA","CGCTCATT","GAGATTCC","ATTCAGAA","GAATTCGT","CTGAAGCT","TAATGCGC","CGGCTATG","TCCGCGAA","TCTCGCGC","AGCGATAG"],
          ["ATTACTCG","TCCGGAGA","CGCTCATT","GAGATTCC","ATTCAGAA","GAATTCGT","CTGAAGCT","TAATGCGC","CGGCTATG","TCCGCGAA","TCTCGCGC","AGCGATAG"],
          ["ATTACTCG","TCCGGAGA","CGCTCATT","GAGATTCC","ATTCAGAA","GAATTCGT","CTGAAGCT","TAATGCGC","CGGCTATG","TCCGCGAA","TCTCGCGC","AGCGATAG"],
          ["ATTACTCG","TCCGGAGA","CGCTCATT","GAGATTCC","ATTCAGAA","GAATTCGT","CTGAAGCT","TAATGCGC","CGGCTATG","TCCGCGAA","TCTCGCGC","AGCGATAG"],
          ["ATTACTCG","TCCGGAGA","CGCTCATT","GAGATTCC","ATTCAGAA","GAATTCGT","CTGAAGCT","TAATGCGC","CGGCTATG","TCCGCGAA","TCTCGCGC","AGCGATAG"]
        ]
      }
    ],
    "IndexNamingRule": {"i5": function(plate, row, col){let n = ('00' + (row+1)).slice(-2); return "D5"+n},
                        "i7": function(plate, row, col){let n = ('00' + (col+1)).slice(-2); return "D7"+n}
                    }
  }
